# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

@cheesename = [
"Abbaye de Belloc",
"Abondance",
"Airedale",
"Alverca",
"Appenzell",
"Aragon",
"Ardrahan",
"Aubisque Pyrenees",
"Beaufort",
"Bierkase",
"Blarney",
"Bleu de Septmoncel",
"Braudostur",
"Brick",
"Canadian Cheddar",
"Cantal",
"Chaumes",
"Cheddar",
"Cheshire",
"Chevres",
"Chontaleno",
"Cojack",
"Colby-Jack",
"Crowley",
"Devon Blue",
"Devon Garland",
"Double Gloucester",
"Edam",
"Edelpilz",
"Esbareich",
"Esrom",
"Filetta",
"Fontal",
"Fourme d Ambert",
"Friesla",
"Fynbo",
"Geitost",
"Gjetost",
"Gloucester",
"Gouda",
"Goutu",
"Grabetto",
"Graddost",
"Greve",
"Herrgardsost",
"Herve",
"Juustoleipa",
"Kikorangi",
"Leerdammer",
"Maasdam",
"Mamirolle",
"Maribo",
"Matocq",
"Meira",
"Menonita",
"Meyer Vintage Gouda",
"Mimolette",
"Mixte",
"Molbo",
"Mondseer",
"Monterey Jack",
"Murol",
"Nokkelost",
"Orla",
"Ossau Fermier",
"Ossau-Iraty",
"Oszczypek",
"Passendale",
"Penamellera",
"Petit Pardou",
"Podhalanski",
"Port-Salut",
"Prastost",
"Provolone",
"Provolone (Australian)",
"Rabacal",
"Ridder",
"Roquefort",
"Royalp Tilsit",
"Saaland Pfarr",
"Sage Derby",
"Saint-Paulin",
"Samso",
"San Simon",
"Schloss",
"Siraz",
"Stilton",
"String",
"Sveciaost",
"Sweet Style Swiss",
"Tasmania Highland Chevre Log",
"Testouri",
"Tete de Moine",
"Tibet",
"Tilsit",
"Toma",
"Tomme de Romans",
"Tommes",
"Toscanello",
"Touree de LAubier",
"Tourmalet",
"Trappe",
"Turunmaa",
"Vasterbottenost",
"Waimata Farmhouse Blue",
"Yorkshire Blue",
]
@cheesename.each do |cheese|

Cheese.create(style: "#{cheese}", family: "semi-soft")
end
