# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

@cheesenamesemisoft = [
"Abbaye de Belloc",
"Abondance",
"Airedale",
"Alverca",
"Appenzell",
"Aragon",
"Ardrahan",
"Aubisque Pyrenees",
"Beaufort",
"Bierkase",
"Blarney",
"Bleu de Septmoncel",
"Braudostur",
"Brick",
"Canadian Cheddar",
"Cantal",
"Chaumes",
"Cheddar",
"Cheshire",
"Chevres",
"Chontaleno",
"Cojack",
"Colby-Jack",
"Crowley",
"Devon Blue",
"Devon Garland",
"Double Gloucester",
"Edam",
"Edelpilz",
"Esbareich",
"Esrom",
"Filetta",
"Fontal",
"Fourme d Ambert",
"Friesla",
"Fynbo",
"Geitost",
"Gjetost",
"Gloucester",
"Gouda",
"Goutu",
"Grabetto",
"Graddost",
"Greve",
"Herrgardsost",
"Herve",
"Juustoleipa",
"Kikorangi",
"Leerdammer",
"Maasdam",
"Mamirolle",
"Maribo",
"Matocq",
"Meira",
"Menonita",
"Meyer Vintage Gouda",
"Mimolette",
"Mixte",
"Molbo",
"Mondseer",
"Monterey Jack",
"Murol",
"Nokkelost",
"Orla",
"Ossau Fermier",
"Ossau-Iraty",
"Oszczypek",
"Passendale",
"Penamellera",
"Petit Pardou",
"Podhalanski",
"Port-Salut",
"Prastost",
"Provolone",
"Provolone (Australian)",
"Rabacal",
"Ridder",
"Roquefort",
"Royalp Tilsit",
"Saaland Pfarr",
"Sage Derby",
"Saint-Paulin",
"Samso",
"San Simon",
"Schloss",
"Siraz",
"Stilton",
"String",
"Sveciaost",
"Sweet Style Swiss",
"Tasmania Highland Chevre Log",
"Testouri",
"Tete de Moine",
"Tibet",
"Tilsit",
"Toma",
"Tomme de Romans",
"Tommes",
"Toscanello",
"Touree de LAubier",
"Tourmalet",
"Trappe",
"Turunmaa",
"Vasterbottenost",
"Waimata Farmhouse Blue",
"Yorkshire Blue",
]
@cheesenamesemisoft.each do |cheese|

Cheese.create(style: "#{cheese}", family: "semi-soft")
end

@cheesenamehard = [
"Abbaye du Mont des Cats",
"Abertam",
"Ackawi",
"Acorn",
"Allgauer Emmentaler",
"Anejo Enchilado",
"Anthoriro",
"Ardi Gasna",
"Asiago",
"Balaton",
"Barrys Bay Cheddar",
"Basing",
"Bavarian Bergkase",
"Beauvoorde",
"Berkswell",
"Blue",
"Boeren Leidenkaas",
"Bra",
"Buffalo",
"Cabrales",
"Caerphilly",
"Cairnsmore",
"Canestrato",
"Castellano",
"Castelleno",
"Castelmagno",
"Castigliano",
"Comte",
"Coolea",
"Coquetdale",
"Corleggy",
"Cotherstone",
"Cotija",
"Coverdale",
"Crayeux de Roncq",
"Crottin de Chavignol",
"Curworthy",
"Cwmtawe Pecorino",
"Denhany Dorset Drum",
"Derby",
"Doolin",
"Dorset Blue Vinney",
"Double Worcester",
"Dry Jack",
"Duddleswell",
"Dunlop",
"Duroblando",
"Dutch Mimolette (Commissiekaas)",
"Emmental",
"Etorki",
"Evora De LAlentejo",
"Finlandia Swiss",
"Fiore Sardo",
"Folded cheese with mint",
"Four Herb Gouda",
"Fourme de Montbrison",
"Fribourgeois",
"Friesekaas",
"Friesian",
"Fromage a Raclette",
"Frying Cheese",
"Gabriel",
"Gammelost",
"Gaperon a lAil",
"Garrotxa",
"Gornyaltajski",
"Gospel Green",
"Gowrie",
"Grafton Village Cheddar",
"Grana",
"Grana Padano",
"Graviera",
"Gruyere",
"Halloumi",
"Halloumy (Australian)",
"Haloumi-Style Cheese",
"Heidi Gruyere",
"Herriot Farmhouse",
"Iberico",
"Idaho Goatster",
"Idiazabal",
"Isle of Mull",
"Jarlsberg",
"Jindi Brie",
"Kadchgall",
"Kefalotyri",
"Laguiole",
"Lairobell",
"Lancashire",
"Laruns",
"Lavistown",
"Leafield",
"Leicester",
"Leyden",
"Lincolnshire Poacher",
"Llanboidy",
"Llanglofan Farmhouse",
"Loch Arthur Farmhouse",
"Longhorn",
"Lou Palou",
"Mahon",
"Malvern",
"Manchego",
"Manur",
"Marble Cheddar",
"Menallack Farmhouse",
"Mihalic Peynir",
"Montasio",
"Monterey Jack Dry",
"Northumberland",
"Orkney Extra Mature Cheddar",
"Oschtjepka",
"Parmesan (Parmigiano)",
"Parmigiano Reggiano",
"Pecorino",
"Pecorino Romano",
"Penbryn",
"Piora",
"Plymouth Cheese",
"Pressato",
"Pyengana Cheddar",
"Queso del Tietar",
"Queso Iberico",
"Queso Majorero",
"Queso Para Frier",
"Raclette",
"Ragusano",
"Reggianito",
"Remedou",
"Ricotta Salata",
"Romano",
"Roncal",
"Saanenkaese",
"Sainte Maure",
"Salers",
"Sancerre",
"Sap Sago",
"Sardo",
"Sardo Egyptian",
"Sbrinz",
"Schabzieger",
"Serat",
"Seriously Strong Cheddar",
"Shelburne Cheddar",
"Shropshire Blue",
"Smoked Gouda",
"Spenwood",
"Sraffordshire Organic",
"Stinking Bishop",
"Swaledale",
"Swiss",
"Syrian (Armenian String)",
"Tala",
"Teifi",
"Tillamook Cheddar",
"Tomme dAbondance",
"Tyn Grug",
"Tyning",
"Ubriaco",
"Wellington",
"Wensleydale",
"White Stilton",
"Xynotyro",
"Yarg Cornish",
"Zamorano",
"Zanetti Grana Padano",
"Zanetti Parmigiano Reggiano",
]

@cheesenamehard.each do |cheese|

  Cheese.create( style: "#{cheese}", family: "hard")
end
